/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 07-dic.-2016 6:18:57 p. m. 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

DROP SEQUENCE IF EXISTS spactividad_pkactividad_seq
;

DROP SEQUENCE IF EXISTS spcargo_pkcargo_seq
;

DROP SEQUENCE IF EXISTS spdetimproductiva_pkdetimproductiva_seq
;

DROP SEQUENCE IF EXISTS spdetproductiva_pkdetpartediario_seq
;

DROP SEQUENCE IF EXISTS spdettransfequipo_pkdettransfequipo_seq
;

DROP SEQUENCE IF EXISTS spdettransfpersonal_pkdettransfpersonal_seq
;

DROP SEQUENCE IF EXISTS speqmodelo_pkeqmodelo_seq
;

DROP SEQUENCE IF EXISTS speqtipo_pkeqtipo_seq
;

DROP SEQUENCE IF EXISTS spequipo_pkequipo_seq
;

DROP SEQUENCE IF EXISTS spgestion_pkgestion_seq
;

DROP SEQUENCE IF EXISTS spimproductiva_pkimproductiva_seq
;

DROP SEQUENCE IF EXISTS spitemobra_pkitemobra_seq
;

DROP SEQUENCE IF EXISTS spordentrabajo_pkordentrabajo_seq
;

DROP SEQUENCE IF EXISTS sppartediario_pkpartediario_seq
;

DROP SEQUENCE IF EXISTS sppersonal_pkpersonal_seq
;

DROP SEQUENCE IF EXISTS sppoligono_pkpoligono_seq
;

DROP SEQUENCE IF EXISTS sptransfequipo_pktransfequipo_seq
;

DROP SEQUENCE IF EXISTS sptransfpersonal_pktransfpersonal_seq
;

DROP SEQUENCE IF EXISTS spturno_pkturno_seq
;

/* Drop Tables */

DROP TABLE IF EXISTS spActividad CASCADE
;

DROP TABLE IF EXISTS spCargo CASCADE
;

DROP TABLE IF EXISTS spDetImproductiva CASCADE
;

DROP TABLE IF EXISTS spDetProductiva CASCADE
;

DROP TABLE IF EXISTS spDetTransfEquipo CASCADE
;

DROP TABLE IF EXISTS spDetTransfPersonal CASCADE
;

DROP TABLE IF EXISTS spEqModelo CASCADE
;

DROP TABLE IF EXISTS spEqTipo CASCADE
;

DROP TABLE IF EXISTS spEquipo CASCADE
;

DROP TABLE IF EXISTS spGestion CASCADE
;

DROP TABLE IF EXISTS spImproductiva CASCADE
;

DROP TABLE IF EXISTS spItemObra CASCADE
;

DROP TABLE IF EXISTS spOrdenTrabajo CASCADE
;

DROP TABLE IF EXISTS spParteDiario CASCADE
;

DROP TABLE IF EXISTS spPersonal CASCADE
;

DROP TABLE IF EXISTS spPoligono CASCADE
;

DROP TABLE IF EXISTS spTransfEquipo CASCADE
;

DROP TABLE IF EXISTS spTransfPersonal CASCADE
;

DROP TABLE IF EXISTS spTurno CASCADE
;

/* Create Tables */

CREATE TABLE spActividad
(
	pkActividad integer NOT NULL   DEFAULT NEXTVAL(('"spactividad_pkactividad_seq"'::text)::regclass),
	fkOrdenTrabajo integer NOT NULL,
	codigo char(2) NOT NULL,
	descripcion varchar(50)
)
;

CREATE TABLE spCargo
(
	pkCargo integer NOT NULL   DEFAULT NEXTVAL(('"spcargo_pkcargo_seq"'::text)::regclass),
	codigo char(3) NOT NULL,
	descripcion varchar(50) NOT NULL
)
;

CREATE TABLE spDetImproductiva
(
	pkDetImproductiva integer NOT NULL   DEFAULT NEXTVAL(('"spdetimproductiva_pkdetimproductiva_seq"'::text)::regclass),
	fkParteDiario integer NOT NULL,
	nroItem integer,
	fkImproductiva integer NOT NULL,
	hrs decimal(10,2)
)
;

CREATE TABLE spDetProductiva
(
	pkDetParteDiario integer NOT NULL   DEFAULT NEXTVAL(('"spdetproductiva_pkdetpartediario_seq"'::text)::regclass),
	fkParteDiario integer NOT NULL,
	nroItem smallint NOT NULL,
	fkItemObra integer NOT NULL,
	grupo smallint NOT NULL,
	hmtoIni decimal(10,2),
	hmtoFin decimal(10,2),
	area decimal(10,2)
)
;

CREATE TABLE spDetTransfEquipo
(
	pkDetTransfEquipo integer NOT NULL   DEFAULT NEXTVAL(('"spdettransfequipo_pkdettransfequipo_seq"'::text)::regclass),
	fkTransfEquipo integer NOT NULL,
	item integer,
	fkEquipo integer NOT NULL,
	observacion varchar(50),
	hmto decimal(10,2)
)
;

CREATE TABLE spDetTransfPersonal
(
	pkDetTransfPersonal integer NOT NULL   DEFAULT NEXTVAL(('"spdettransfpersonal_pkdettransfpersonal_seq"'::text)::regclass),
	fkTransfPersonal integer NOT NULL,
	item integer,
	fkPersonal integer NOT NULL,
	observacion varchar(50)
)
;

CREATE TABLE spEqModelo
(
	pkEqModelo integer NOT NULL   DEFAULT NEXTVAL(('"speqmodelo_pkeqmodelo_seq"'::text)::regclass),
	fkEqTipo integer NOT NULL,
	codigo char(2) NOT NULL,
	descripcion varchar(25)
)
;

CREATE TABLE spEqTipo
(
	pkEqTipo integer NOT NULL   DEFAULT NEXTVAL(('"speqtipo_pkeqtipo_seq"'::text)::regclass),
	codigo char(2) NOT NULL,
	descripcion varchar(25)
)
;

CREATE TABLE spEquipo
(
	pkEquipo integer NOT NULL   DEFAULT NEXTVAL(('"spequipo_pkequipo_seq"'::text)::regclass),
	fkTipoEquipo integer NOT NULL,
	fkModelo integer NOT NULL,
	codigo char(9) NOT NULL,
	fkTipoContrato char(1) NOT NULL,
	fechaIngreso date,
	fkOrdenTrabajo integer NOT NULL,
	descripcion varchar(50)
)
;

CREATE TABLE spGestion
(
	pkGestion integer NOT NULL   DEFAULT NEXTVAL(('"spgestion_pkgestion_seq"'::text)::regclass),
	codigo char(2) NOT NULL,
	fechaIni date,
	fechaFin date,
	estado char(1)
)
;

CREATE TABLE spImproductiva
(
	pkImproductiva integer NOT NULL   DEFAULT NEXTVAL(('"spimproductiva_pkimproductiva_seq"'::text)::regclass),
	codigo char(4),
	descripcion varchar(50)
)
;

CREATE TABLE spItemObra
(
	pkItemObra integer NOT NULL   DEFAULT NEXTVAL(('"spitemobra_pkitemobra_seq"'::text)::regclass),
	fkOrdenTrabajo integer NOT NULL,
	fkPoligono integer NOT NULL,
	fkActividad integer NOT NULL,
	codigo char(6) NOT NULL,
	descripcion varchar(50),
	areaTrab decimal(10,2),
	rendimiento decimal(10,2)
)
;

CREATE TABLE spOrdenTrabajo
(
	pkOrdenTrabajo integer NOT NULL   DEFAULT NEXTVAL(('"spordentrabajo_pkordentrabajo_seq"'::text)::regclass),
	codigo char(3) NOT NULL,
	fkGestion integer NOT NULL,
	nombre varchar(50),
	supervisor varchar(50),
	areaEstimada decimal(10,2),
	estado char(1),
	data char(6)
)
;

CREATE TABLE spParteDiario
(
	pkParteDiario integer NOT NULL   DEFAULT NEXTVAL(('"sppartediario_pkpartediario_seq"'::text)::regclass),
	fkOrdenTrabajo integer NOT NULL,
	fecha date NOT NULL,
	fkEquipo integer NOT NULL,
	fkTurno integer NOT NULL,
	fkOperador integer NOT NULL,
	fkAyudante integer NOT NULL,
	observacion varchar(50)
)
;

CREATE TABLE spPersonal
(
	pkPersonal integer NOT NULL   DEFAULT NEXTVAL(('"sppersonal_pkpersonal_seq"'::text)::regclass),
	fechaIngreso date,
	nombreComp varchar(50),
	apellidos varchar(50),
	direccion varchar(50),
	telefono varchar(50),
	ci varchar(25),
	fechaNac date,
	fkcargo integer,
	fkOrdenTrabajo integer,
	email varchar(25)
)
;

CREATE TABLE spPoligono
(
	pkPoligono integer NOT NULL   DEFAULT NEXTVAL(('"sppoligono_pkpoligono_seq"'::text)::regclass),
	fkOrdenTrabajo integer NOT NULL,
	codigo char(3) NOT NULL,
	descripcion varchar(50)
)
;

CREATE TABLE spTransfEquipo
(
	pkTransfEquipo integer NOT NULL   DEFAULT NEXTVAL(('"sptransfequipo_pktransfequipo_seq"'::text)::regclass),
	codigo char(4) NOT NULL,
	fkGestion integer NOT NULL,
	fecha date,
	fkOrdenOrigen integer NOT NULL,
	fkOrdenDestino integer NOT NULL,
	observacion varchar(50),
	data char(7) NOT NULL,
	estado char(1) NOT NULL
)
;

CREATE TABLE spTransfPersonal
(
	pkTransfPersonal integer NOT NULL   DEFAULT NEXTVAL(('"sptransfpersonal_pktransfpersonal_seq"'::text)::regclass),
	codigo char(4) NOT NULL,
	fkGestion integer NOT NULL,
	fecha date,
	fkOrdenOrigen integer NOT NULL,
	fkOrdenDestino integer NOT NULL,
	observacion varchar(50),
	data char(7),
	estado char(1)
)
;

CREATE TABLE spTurno
(
	pkTurno integer NOT NULL   DEFAULT NEXTVAL(('"spturno_pkturno_seq"'::text)::regclass),
	codigo varchar(3),
	descripcion varchar(25),
	fkOrdenTrabajo integer
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE spActividad ADD CONSTRAINT PK_spActividad
	PRIMARY KEY (pkActividad)
;

CREATE INDEX IXFK_spActividad_spOrdenTrabajo ON spActividad (fkOrdenTrabajo ASC)
;

ALTER TABLE spCargo ADD CONSTRAINT PK_spCargo
	PRIMARY KEY (pkCargo)
;

ALTER TABLE spDetImproductiva ADD CONSTRAINT PK_Table1
	PRIMARY KEY (pkDetImproductiva)
;

CREATE INDEX IXFK_spDetImproductiva_spImproductiva ON spDetImproductiva (fkImproductiva ASC)
;

CREATE INDEX IXFK_spDetImproductiva_spParteDiario ON spDetImproductiva (fkParteDiario ASC)
;

ALTER TABLE spDetProductiva ADD CONSTRAINT PK_spDetParteDiario
	PRIMARY KEY (pkDetParteDiario)
;

CREATE INDEX IXFK_spDetProductiva_spItemObra ON spDetProductiva (fkItemObra ASC)
;

CREATE INDEX IXFK_spDetProductiva_spParteDiario ON spDetProductiva (fkParteDiario ASC)
;

ALTER TABLE spDetTransfEquipo ADD CONSTRAINT PK_spDetTransfEquipo
	PRIMARY KEY (pkDetTransfEquipo)
;

CREATE INDEX IXFK_spDetTransfEquipo_spEquipo ON spDetTransfEquipo (fkEquipo ASC)
;

CREATE INDEX IXFK_spDetTransfEquipo_spTransfEquipo ON spDetTransfEquipo (fkTransfEquipo ASC)
;

ALTER TABLE spDetTransfPersonal ADD CONSTRAINT PK_spDetTransfPersonal
	PRIMARY KEY (pkDetTransfPersonal)
;

CREATE INDEX IXFK_spDetTransfPersonal_spPersonal ON spDetTransfPersonal (fkPersonal ASC)
;

CREATE INDEX IXFK_spDetTransfPersonal_spTransfPersonal ON spDetTransfPersonal (fkTransfPersonal ASC)
;

ALTER TABLE spEqModelo ADD CONSTRAINT PK_spEqModelo
	PRIMARY KEY (pkEqModelo)
;

CREATE INDEX IXFK_spEqModelo_spEqTipo ON spEqModelo (fkEqTipo ASC)
;

ALTER TABLE spEqTipo ADD CONSTRAINT PK_spEqTipo
	PRIMARY KEY (pkEqTipo)
;

ALTER TABLE spEquipo ADD CONSTRAINT PK_spEquipo
	PRIMARY KEY (pkEquipo)
;

CREATE INDEX IXFK_spEquipo_spEqModelo ON spEquipo (fkModelo ASC)
;

CREATE INDEX IXFK_spEquipo_spEqTipo ON spEquipo (fkTipoEquipo ASC)
;

CREATE INDEX IXFK_spEquipo_spOrdenTrabajo ON spEquipo (fkOrdenTrabajo ASC)
;

ALTER TABLE spGestion ADD CONSTRAINT PK_spGestion
	PRIMARY KEY (pkGestion)
;

ALTER TABLE spImproductiva ADD CONSTRAINT PK_spImproductiva
	PRIMARY KEY (pkImproductiva)
;

ALTER TABLE spItemObra ADD CONSTRAINT PK_spItemObra
	PRIMARY KEY (pkItemObra)
;

CREATE INDEX IXFK_spItemObra_spActividad ON spItemObra (fkActividad ASC)
;

CREATE INDEX IXFK_spItemObra_spOrdenTrabajo ON spItemObra (fkOrdenTrabajo ASC)
;

CREATE INDEX IXFK_spItemObra_spPoligono ON spItemObra (fkPoligono ASC)
;

ALTER TABLE spOrdenTrabajo ADD CONSTRAINT PK_spOrdenTrabajo
	PRIMARY KEY (pkOrdenTrabajo)
;

CREATE INDEX IXFK_spOrdenTrabajo_spGestion ON spOrdenTrabajo (fkGestion ASC)
;

ALTER TABLE spParteDiario ADD CONSTRAINT PK_ParteDiario
	PRIMARY KEY (pkParteDiario)
;

CREATE INDEX IXFK_spParteDiario_spEquipo ON spParteDiario (fkEquipo ASC)
;

CREATE INDEX IXFK_spParteDiario_spOrdenTrabajo ON spParteDiario (fkOrdenTrabajo ASC)
;

CREATE INDEX IXFK_spParteDiario_spPersonal ON spParteDiario (fkOperador ASC)
;

CREATE INDEX IXFK_spParteDiario_spPersonal_02 ON spParteDiario (fkAyudante ASC)
;

CREATE INDEX IXFK_spParteDiario_spTurno ON spParteDiario (fkTurno ASC)
;

ALTER TABLE spPersonal ADD CONSTRAINT PK_spPersonal
	PRIMARY KEY (pkPersonal)
;

CREATE INDEX IXFK_spPersonal_spCargo ON spPersonal (fkcargo ASC)
;

CREATE INDEX IXFK_spPersonal_spOrdenTrabajo ON spPersonal (fkOrdenTrabajo ASC)
;

ALTER TABLE spPoligono ADD CONSTRAINT PK_spPoligono
	PRIMARY KEY (pkPoligono)
;

CREATE INDEX IXFK_spPoligono_spOrdenTrabajo ON spPoligono (fkOrdenTrabajo ASC)
;

ALTER TABLE spTransfEquipo ADD CONSTRAINT PK_spTransfEquipo
	PRIMARY KEY (pkTransfEquipo)
;

CREATE INDEX IXFK_spTransfEquipo_spGestion ON spTransfEquipo (fkGestion ASC)
;

CREATE INDEX IXFK_spTransfEquipo_spOrdenTrabajo ON spTransfEquipo (fkOrdenOrigen ASC)
;

CREATE INDEX IXFK_spTransfEquipo_spOrdenTrabajo_02 ON spTransfEquipo (fkOrdenDestino ASC)
;

ALTER TABLE spTransfPersonal ADD CONSTRAINT PK_spTransfPersonal
	PRIMARY KEY (pkTransfPersonal)
;

CREATE INDEX IXFK_spTransfPersonal_spGestion ON spTransfPersonal (fkGestion ASC)
;

CREATE INDEX IXFK_spTransfPersonal_spOrdenTrabajo ON spTransfPersonal (fkOrdenOrigen ASC)
;

CREATE INDEX IXFK_spTransfPersonal_spOrdenTrabajo_02 ON spTransfPersonal (fkOrdenDestino ASC)
;

ALTER TABLE spTurno ADD CONSTRAINT PK_spTurno
	PRIMARY KEY (pkTurno)
;

CREATE INDEX IXFK_spTurno_spOrdenTrabajo ON spTurno (fkOrdenTrabajo ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE spActividad ADD CONSTRAINT FK_spActividad_spOrdenTrabajo
	FOREIGN KEY (fkOrdenTrabajo) REFERENCES spOrdenTrabajo (pkOrdenTrabajo) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE spDetImproductiva ADD CONSTRAINT FK_spDetImproductiva_spImproductiva
	FOREIGN KEY (fkImproductiva) REFERENCES spImproductiva (pkImproductiva) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE spDetImproductiva ADD CONSTRAINT FK_spDetImproductiva_spParteDiario
	FOREIGN KEY (fkParteDiario) REFERENCES spParteDiario (pkParteDiario) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE spDetProductiva ADD CONSTRAINT FK_spDetProductiva_spItemObra
	FOREIGN KEY (fkItemObra) REFERENCES spItemObra (pkItemObra) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE spDetProductiva ADD CONSTRAINT FK_spDetProductiva_spParteDiario
	FOREIGN KEY (fkParteDiario) REFERENCES spParteDiario (pkParteDiario) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE spDetTransfEquipo ADD CONSTRAINT FK_spDetTransfEquipo_spEquipo
	FOREIGN KEY (fkEquipo) REFERENCES spEquipo (pkEquipo) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE spDetTransfEquipo ADD CONSTRAINT FK_spDetTransfEquipo_spTransfEquipo
	FOREIGN KEY (fkTransfEquipo) REFERENCES spTransfEquipo (pkTransfEquipo) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE spDetTransfPersonal ADD CONSTRAINT FK_spDetTransfPersonal_spPersonal
	FOREIGN KEY (fkPersonal) REFERENCES spPersonal (pkPersonal) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE spDetTransfPersonal ADD CONSTRAINT FK_spDetTransfPersonal_spTransfPersonal
	FOREIGN KEY (fkTransfPersonal) REFERENCES spTransfPersonal (pkTransfPersonal) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE spEqModelo ADD CONSTRAINT FK_spEqModelo_spEqTipo
	FOREIGN KEY (fkEqTipo) REFERENCES spEqTipo (pkEqTipo) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE spEquipo ADD CONSTRAINT FK_spEquipo_spEqModelo
	FOREIGN KEY (fkModelo) REFERENCES spEqModelo (pkEqModelo) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE spEquipo ADD CONSTRAINT FK_spEquipo_spEqTipo
	FOREIGN KEY (fkTipoEquipo) REFERENCES spEqTipo (pkEqTipo) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE spEquipo ADD CONSTRAINT FK_spEquipo_spOrdenTrabajo
	FOREIGN KEY (fkOrdenTrabajo) REFERENCES spOrdenTrabajo (pkOrdenTrabajo) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE spItemObra ADD CONSTRAINT FK_spItemObra_spActividad
	FOREIGN KEY (fkActividad) REFERENCES spActividad (pkActividad) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE spItemObra ADD CONSTRAINT FK_spItemObra_spOrdenTrabajo
	FOREIGN KEY (fkOrdenTrabajo) REFERENCES spOrdenTrabajo (pkOrdenTrabajo) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE spItemObra ADD CONSTRAINT FK_spItemObra_spPoligono
	FOREIGN KEY (fkPoligono) REFERENCES spPoligono (pkPoligono) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE spOrdenTrabajo ADD CONSTRAINT FK_spOrdenTrabajo_spGestion
	FOREIGN KEY (fkGestion) REFERENCES spGestion (pkGestion) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE spParteDiario ADD CONSTRAINT FK_spParteDiario_spEquipo
	FOREIGN KEY (fkEquipo) REFERENCES spEquipo (pkEquipo) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE spParteDiario ADD CONSTRAINT FK_spParteDiario_spOrdenTrabajo
	FOREIGN KEY (fkOrdenTrabajo) REFERENCES spOrdenTrabajo (pkOrdenTrabajo) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE spParteDiario ADD CONSTRAINT FK_spParteDiario_spPersonal
	FOREIGN KEY (fkOperador) REFERENCES spPersonal (pkPersonal) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE spParteDiario ADD CONSTRAINT FK_spParteDiario_spPersonal_02
	FOREIGN KEY (fkAyudante) REFERENCES spPersonal (pkPersonal) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE spParteDiario ADD CONSTRAINT FK_spParteDiario_spTurno
	FOREIGN KEY (fkTurno) REFERENCES spTurno (pkTurno) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE spPersonal ADD CONSTRAINT FK_spPersonal_spCargo
	FOREIGN KEY (fkcargo) REFERENCES spCargo (pkCargo) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE spPersonal ADD CONSTRAINT FK_spPersonal_spOrdenTrabajo
	FOREIGN KEY (fkOrdenTrabajo) REFERENCES spOrdenTrabajo (pkOrdenTrabajo) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE spPoligono ADD CONSTRAINT FK_spPoligono_spOrdenTrabajo
	FOREIGN KEY (fkOrdenTrabajo) REFERENCES spOrdenTrabajo (pkOrdenTrabajo) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE spTransfEquipo ADD CONSTRAINT FK_spTransfEquipo_spGestion
	FOREIGN KEY (fkGestion) REFERENCES spGestion (pkGestion) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE spTransfEquipo ADD CONSTRAINT FK_spTransfEquipo_spOrdenTrabajo_02
	FOREIGN KEY (fkOrdenDestino) REFERENCES spOrdenTrabajo (pkOrdenTrabajo) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE spTransfPersonal ADD CONSTRAINT FK_spTransfPersonal_spGestion
	FOREIGN KEY (fkGestion) REFERENCES spGestion (pkGestion) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE spTransfPersonal ADD CONSTRAINT FK_spTransfPersonal_spOrdenTrabajo
	FOREIGN KEY (fkOrdenOrigen) REFERENCES spOrdenTrabajo (pkOrdenTrabajo) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE spTransfPersonal ADD CONSTRAINT FK_spTransfPersonal_spOrdenTrabajo_02
	FOREIGN KEY (fkOrdenDestino) REFERENCES spOrdenTrabajo (pkOrdenTrabajo) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE spTurno ADD CONSTRAINT FK_spTurno_spOrdenTrabajo
	FOREIGN KEY (fkOrdenTrabajo) REFERENCES spOrdenTrabajo (pkOrdenTrabajo) ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

CREATE SEQUENCE spactividad_pkactividad_seq INCREMENT 1 START 1
;

CREATE SEQUENCE spcargo_pkcargo_seq INCREMENT 1 START 1
;

CREATE SEQUENCE spdetimproductiva_pkdetimproductiva_seq INCREMENT 1 START 1
;

CREATE SEQUENCE spdetproductiva_pkdetpartediario_seq INCREMENT 1 START 1
;

CREATE SEQUENCE spdettransfequipo_pkdettransfequipo_seq INCREMENT 1 START 1
;

CREATE SEQUENCE spdettransfpersonal_pkdettransfpersonal_seq INCREMENT 1 START 1
;

CREATE SEQUENCE speqmodelo_pkeqmodelo_seq INCREMENT 1 START 1
;

CREATE SEQUENCE speqtipo_pkeqtipo_seq INCREMENT 1 START 1
;

CREATE SEQUENCE spequipo_pkequipo_seq INCREMENT 1 START 1
;

CREATE SEQUENCE spgestion_pkgestion_seq INCREMENT 1 START 1
;

CREATE SEQUENCE spimproductiva_pkimproductiva_seq INCREMENT 1 START 1
;

CREATE SEQUENCE spitemobra_pkitemobra_seq INCREMENT 1 START 1
;

CREATE SEQUENCE spordentrabajo_pkordentrabajo_seq INCREMENT 1 START 1
;

CREATE SEQUENCE sppartediario_pkpartediario_seq INCREMENT 1 START 1
;

CREATE SEQUENCE sppersonal_pkpersonal_seq INCREMENT 1 START 1
;

CREATE SEQUENCE sppoligono_pkpoligono_seq INCREMENT 1 START 1
;

CREATE SEQUENCE sptransfequipo_pktransfequipo_seq INCREMENT 1 START 1
;

CREATE SEQUENCE sptransfpersonal_pktransfpersonal_seq INCREMENT 1 START 1
;

COMMENT ON TABLE spTurno
	IS 'Esto se define dentro de cada obra,  algunas pueden tener mas de 1 turno  cada turno esta dividido en horas que se ejecutaran'
;

CREATE SEQUENCE spturno_pkturno_seq INCREMENT 1 START 1
;
