package com.grupo06sa.emailweb.modelos;
// Generated 25-06-2017 07:52:36 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Spcargo generated by hbm2java
 */
public class Spcargo  implements java.io.Serializable {


     private int pkcargo;
     private String codigo;
     private String descripcion;
     private Set sppersonals = new HashSet(0);

    public Spcargo() {
    }

    public Spcargo(int pkcargo, String codigo, String descripcion) {
        this.pkcargo = pkcargo;
        this.codigo = codigo;
        this.descripcion = descripcion;
    }
    public Spcargo(int pkcargo, String codigo, String descripcion, Set sppersonals) {
       this.pkcargo = pkcargo;
       this.codigo = codigo;
       this.descripcion = descripcion;
       this.sppersonals = sppersonals;
    }
   
    public int getPkcargo() {
        return this.pkcargo;
    }
    
    public void setPkcargo(int pkcargo) {
        this.pkcargo = pkcargo;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getSppersonals() {
        return this.sppersonals;
    }
    
    public void setSppersonals(Set sppersonals) {
        this.sppersonals = sppersonals;
    }

    @Override
    public String toString(){
        return "[codigo => " + this.codigo +", descripcion => " + this.descripcion +  "]";
    }
}


