package com.grupo06sa.emailweb.modelos;
// Generated 25-06-2017 07:52:36 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Spdetproductiva generated by hbm2java
 */
public class Spdetproductiva  implements java.io.Serializable {


     private int pkdetpartediario;
     private Spitemobra spitemobra;
     private Sppartediario sppartediario;
     private short nroitem;
     private short grupo;
     private BigDecimal hmtoini;
     private BigDecimal hmtofin;
     private BigDecimal area;

    public Spdetproductiva() {
    }

	
    public Spdetproductiva(int pkdetpartediario, Spitemobra spitemobra, Sppartediario sppartediario, short nroitem, short grupo) {
        this.pkdetpartediario = pkdetpartediario;
        this.spitemobra = spitemobra;
        this.sppartediario = sppartediario;
        this.nroitem = nroitem;
        this.grupo = grupo;
    }
    public Spdetproductiva(int pkdetpartediario, Spitemobra spitemobra, Sppartediario sppartediario, short nroitem, short grupo, BigDecimal hmtoini, BigDecimal hmtofin, BigDecimal area) {
       this.pkdetpartediario = pkdetpartediario;
       this.spitemobra = spitemobra;
       this.sppartediario = sppartediario;
       this.nroitem = nroitem;
       this.grupo = grupo;
       this.hmtoini = hmtoini;
       this.hmtofin = hmtofin;
       this.area = area;
    }
   
    public int getPkdetpartediario() {
        return this.pkdetpartediario;
    }
    
    public void setPkdetpartediario(int pkdetpartediario) {
        this.pkdetpartediario = pkdetpartediario;
    }
    public Spitemobra getSpitemobra() {
        return this.spitemobra;
    }
    
    public void setSpitemobra(Spitemobra spitemobra) {
        this.spitemobra = spitemobra;
    }
    public Sppartediario getSppartediario() {
        return this.sppartediario;
    }
    
    public void setSppartediario(Sppartediario sppartediario) {
        this.sppartediario = sppartediario;
    }
    public short getNroitem() {
        return this.nroitem;
    }
    
    public void setNroitem(short nroitem) {
        this.nroitem = nroitem;
    }
    public short getGrupo() {
        return this.grupo;
    }
    
    public void setGrupo(short grupo) {
        this.grupo = grupo;
    }
    public BigDecimal getHmtoini() {
        return this.hmtoini;
    }
    
    public void setHmtoini(BigDecimal hmtoini) {
        this.hmtoini = hmtoini;
    }
    public BigDecimal getHmtofin() {
        return this.hmtofin;
    }
    
    public void setHmtofin(BigDecimal hmtofin) {
        this.hmtofin = hmtofin;
    }
    public BigDecimal getArea() {
        return this.area;
    }
    
    public void setArea(BigDecimal area) {
        this.area = area;
    }




}


