package com.grupo06sa.emailweb.modelos;
// Generated 25-06-2017 07:52:36 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Spdettransfequipo generated by hbm2java
 */
public class Spdettransfequipo  implements java.io.Serializable {


     private int pkdettransfequipo;
     private Spequipo spequipo;
     private Sptransfequipo sptransfequipo;
     private short item;
     private String observacion;
     private BigDecimal hmto;

    public Spdettransfequipo() {
    }

	
    public Spdettransfequipo(int pkdettransfequipo, Spequipo spequipo, Sptransfequipo sptransfequipo, short item) {
        this.pkdettransfequipo = pkdettransfequipo;
        this.spequipo = spequipo;
        this.sptransfequipo = sptransfequipo;
        this.item = item;
    }
    public Spdettransfequipo(int pkdettransfequipo, Spequipo spequipo, Sptransfequipo sptransfequipo, short item, String observacion, BigDecimal hmto) {
       this.pkdettransfequipo = pkdettransfequipo;
       this.spequipo = spequipo;
       this.sptransfequipo = sptransfequipo;
       this.item = item;
       this.observacion = observacion;
       this.hmto = hmto;
    }
   
    public int getPkdettransfequipo() {
        return this.pkdettransfequipo;
    }
    
    public void setPkdettransfequipo(int pkdettransfequipo) {
        this.pkdettransfequipo = pkdettransfequipo;
    }
    public Spequipo getSpequipo() {
        return this.spequipo;
    }
    
    public void setSpequipo(Spequipo spequipo) {
        this.spequipo = spequipo;
    }
    public Sptransfequipo getSptransfequipo() {
        return this.sptransfequipo;
    }
    
    public void setSptransfequipo(Sptransfequipo sptransfequipo) {
        this.sptransfequipo = sptransfequipo;
    }
    public short getItem() {
        return this.item;
    }
    
    public void setItem(short item) {
        this.item = item;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
    public BigDecimal getHmto() {
        return this.hmto;
    }
    
    public void setHmto(BigDecimal hmto) {
        this.hmto = hmto;
    }




}


