package com.grupo06sa.emailweb.modelos;
// Generated 25-06-2017 07:52:36 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Spgestion generated by hbm2java
 */
public class Spgestion  implements java.io.Serializable {


     private int pkgestion;
     private String codigo;
     private Date fechaini;
     private Date fechafin;
     private Character estado;
     private Set sptransfequipos = new HashSet(0);
     private Set spordentrabajos = new HashSet(0);
     private Set sptransfpersonals = new HashSet(0);

    public Spgestion() {
    }

	
    public Spgestion(int pkgestion, String codigo) {
        this.pkgestion = pkgestion;
        this.codigo = codigo;
    }
    public Spgestion(int pkgestion, String codigo, Date fechaini, Date fechafin, Character estado, Set sptransfequipos, Set spordentrabajos, Set sptransfpersonals) {
       this.pkgestion = pkgestion;
       this.codigo = codigo;
       this.fechaini = fechaini;
       this.fechafin = fechafin;
       this.estado = estado;
       this.sptransfequipos = sptransfequipos;
       this.spordentrabajos = spordentrabajos;
       this.sptransfpersonals = sptransfpersonals;
    }
   
    public int getPkgestion() {
        return this.pkgestion;
    }
    
    public void setPkgestion(int pkgestion) {
        this.pkgestion = pkgestion;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public Date getFechaini() {
        return this.fechaini;
    }
    
    public void setFechaini(Date fechaini) {
        this.fechaini = fechaini;
    }
    public Date getFechafin() {
        return this.fechafin;
    }
    
    public void setFechafin(Date fechafin) {
        this.fechafin = fechafin;
    }
    public Character getEstado() {
        return this.estado;
    }
    
    public void setEstado(Character estado) {
        this.estado = estado;
    }
    public Set getSptransfequipos() {
        return this.sptransfequipos;
    }
    
    public void setSptransfequipos(Set sptransfequipos) {
        this.sptransfequipos = sptransfequipos;
    }
    public Set getSpordentrabajos() {
        return this.spordentrabajos;
    }
    
    public void setSpordentrabajos(Set spordentrabajos) {
        this.spordentrabajos = spordentrabajos;
    }
    public Set getSptransfpersonals() {
        return this.sptransfpersonals;
    }
    
    public void setSptransfpersonals(Set sptransfpersonals) {
        this.sptransfpersonals = sptransfpersonals;
    }




}


