package com.grupo06sa.emailweb.modelos;
// Generated 25-06-2017 07:52:36 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Spimproductiva generated by hbm2java
 */
public class Spimproductiva  implements java.io.Serializable {


     private int pkimproductiva;
     private String codigo;
     private String descripcion;
     private Set spdetimproductivas = new HashSet(0);

    public Spimproductiva() {
    }

	
    public Spimproductiva(int pkimproductiva) {
        this.pkimproductiva = pkimproductiva;
    }
    public Spimproductiva(int pkimproductiva, String codigo, String descripcion, Set spdetimproductivas) {
       this.pkimproductiva = pkimproductiva;
       this.codigo = codigo;
       this.descripcion = descripcion;
       this.spdetimproductivas = spdetimproductivas;
    }
   
    public int getPkimproductiva() {
        return this.pkimproductiva;
    }
    
    public void setPkimproductiva(int pkimproductiva) {
        this.pkimproductiva = pkimproductiva;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getSpdetimproductivas() {
        return this.spdetimproductivas;
    }
    
    public void setSpdetimproductivas(Set spdetimproductivas) {
        this.spdetimproductivas = spdetimproductivas;
    }




}


