package com.grupo06sa.emailweb.modelos;
// Generated 25-06-2017 07:52:36 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Spordentrabajo generated by hbm2java
 */
public class Spordentrabajo  implements java.io.Serializable {


     private int pkordentrabajo;
     private Spgestion spgestion;
     private String codigo;
     private String nombre;
     private String supervisor;
     private BigDecimal areaestimada;
     private Character estado;
     private String data;
     private Set spequipos = new HashSet(0);
     private Set sppartediarios = new HashSet(0);
     private Set sptransfpersonalsForFkordendestino = new HashSet(0);
     private Set spactividads = new HashSet(0);
     private Set sppoligonos = new HashSet(0);
     private Set spitemobras = new HashSet(0);
     private Set sppersonals = new HashSet(0);
     private Set sptransfpersonalsForFkordenorigen = new HashSet(0);
     private Set spturnos = new HashSet(0);
     private Set sptransfequipos = new HashSet(0);

    public Spordentrabajo() {
    }

	
    public Spordentrabajo(int pkordentrabajo, Spgestion spgestion, String codigo) {
        this.pkordentrabajo = pkordentrabajo;
        this.spgestion = spgestion;
        this.codigo = codigo;
    }
    public Spordentrabajo(int pkordentrabajo, Spgestion spgestion, String codigo, String nombre, String supervisor, BigDecimal areaestimada, Character estado, String data, Set spequipos, Set sppartediarios, Set sptransfpersonalsForFkordendestino, Set spactividads, Set sppoligonos, Set spitemobras, Set sppersonals, Set sptransfpersonalsForFkordenorigen, Set spturnos, Set sptransfequipos) {
       this.pkordentrabajo = pkordentrabajo;
       this.spgestion = spgestion;
       this.codigo = codigo;
       this.nombre = nombre;
       this.supervisor = supervisor;
       this.areaestimada = areaestimada;
       this.estado = estado;
       this.data = data;
       this.spequipos = spequipos;
       this.sppartediarios = sppartediarios;
       this.sptransfpersonalsForFkordendestino = sptransfpersonalsForFkordendestino;
       this.spactividads = spactividads;
       this.sppoligonos = sppoligonos;
       this.spitemobras = spitemobras;
       this.sppersonals = sppersonals;
       this.sptransfpersonalsForFkordenorigen = sptransfpersonalsForFkordenorigen;
       this.spturnos = spturnos;
       this.sptransfequipos = sptransfequipos;
    }
   
    public int getPkordentrabajo() {
        return this.pkordentrabajo;
    }
    
    public void setPkordentrabajo(int pkordentrabajo) {
        this.pkordentrabajo = pkordentrabajo;
    }
    public Spgestion getSpgestion() {
        return this.spgestion;
    }
    
    public void setSpgestion(Spgestion spgestion) {
        this.spgestion = spgestion;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getSupervisor() {
        return this.supervisor;
    }
    
    public void setSupervisor(String supervisor) {
        this.supervisor = supervisor;
    }
    public BigDecimal getAreaestimada() {
        return this.areaestimada;
    }
    
    public void setAreaestimada(BigDecimal areaestimada) {
        this.areaestimada = areaestimada;
    }
    public Character getEstado() {
        return this.estado;
    }
    
    public void setEstado(Character estado) {
        this.estado = estado;
    }
    public String getData() {
        return this.data;
    }
    
    public void setData(String data) {
        this.data = data;
    }
    public Set getSpequipos() {
        return this.spequipos;
    }
    
    public void setSpequipos(Set spequipos) {
        this.spequipos = spequipos;
    }
    public Set getSppartediarios() {
        return this.sppartediarios;
    }
    
    public void setSppartediarios(Set sppartediarios) {
        this.sppartediarios = sppartediarios;
    }
    public Set getSptransfpersonalsForFkordendestino() {
        return this.sptransfpersonalsForFkordendestino;
    }
    
    public void setSptransfpersonalsForFkordendestino(Set sptransfpersonalsForFkordendestino) {
        this.sptransfpersonalsForFkordendestino = sptransfpersonalsForFkordendestino;
    }
    public Set getSpactividads() {
        return this.spactividads;
    }
    
    public void setSpactividads(Set spactividads) {
        this.spactividads = spactividads;
    }
    public Set getSppoligonos() {
        return this.sppoligonos;
    }
    
    public void setSppoligonos(Set sppoligonos) {
        this.sppoligonos = sppoligonos;
    }
    public Set getSpitemobras() {
        return this.spitemobras;
    }
    
    public void setSpitemobras(Set spitemobras) {
        this.spitemobras = spitemobras;
    }
    public Set getSppersonals() {
        return this.sppersonals;
    }
    
    public void setSppersonals(Set sppersonals) {
        this.sppersonals = sppersonals;
    }
    public Set getSptransfpersonalsForFkordenorigen() {
        return this.sptransfpersonalsForFkordenorigen;
    }
    
    public void setSptransfpersonalsForFkordenorigen(Set sptransfpersonalsForFkordenorigen) {
        this.sptransfpersonalsForFkordenorigen = sptransfpersonalsForFkordenorigen;
    }
    public Set getSpturnos() {
        return this.spturnos;
    }
    
    public void setSpturnos(Set spturnos) {
        this.spturnos = spturnos;
    }
    public Set getSptransfequipos() {
        return this.sptransfequipos;
    }
    
    public void setSptransfequipos(Set sptransfequipos) {
        this.sptransfequipos = sptransfequipos;
    }




}


