package com.grupo06sa.emailweb.modelos;
// Generated 25-06-2017 07:52:36 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Sppoligono generated by hbm2java
 */
public class Sppoligono  implements java.io.Serializable {


     private int pkpoligono;
     private Spordentrabajo spordentrabajo;
     private String codigo;
     private String descripcion;
     private Set spitemobras = new HashSet(0);

    public Sppoligono() {
    }

	
    public Sppoligono(int pkpoligono, Spordentrabajo spordentrabajo, String codigo) {
        this.pkpoligono = pkpoligono;
        this.spordentrabajo = spordentrabajo;
        this.codigo = codigo;
    }
    public Sppoligono(int pkpoligono, Spordentrabajo spordentrabajo, String codigo, String descripcion, Set spitemobras) {
       this.pkpoligono = pkpoligono;
       this.spordentrabajo = spordentrabajo;
       this.codigo = codigo;
       this.descripcion = descripcion;
       this.spitemobras = spitemobras;
    }
   
    public int getPkpoligono() {
        return this.pkpoligono;
    }
    
    public void setPkpoligono(int pkpoligono) {
        this.pkpoligono = pkpoligono;
    }
    public Spordentrabajo getSpordentrabajo() {
        return this.spordentrabajo;
    }
    
    public void setSpordentrabajo(Spordentrabajo spordentrabajo) {
        this.spordentrabajo = spordentrabajo;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getSpitemobras() {
        return this.spitemobras;
    }
    
    public void setSpitemobras(Set spitemobras) {
        this.spitemobras = spitemobras;
    }
    @Override
    public String toString(){
        return "[ id : " + this.getPkpoligono() + ", codigo : " + this.getCodigo() + ", descripcion : " + this.getDescripcion() + "]";
    }
}


