package com.grupo06sa.emailweb.modelos;
// Generated 25-06-2017 07:52:36 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Sptransfequipo generated by hbm2java
 */
public class Sptransfequipo  implements java.io.Serializable {


     private int pktransfequipo;
     private Spgestion spgestion;
     private Spordentrabajo spordentrabajo;
     private String codigo;
     private Date fecha;
     private int fkordenorigen;
     private String observacion;
     private String data;
     private char estado;
     private Set spdettransfequipos = new HashSet(0);

    public Sptransfequipo() {
    }

	
    public Sptransfequipo(int pktransfequipo, Spgestion spgestion, Spordentrabajo spordentrabajo, String codigo, int fkordenorigen, String data, char estado) {
        this.pktransfequipo = pktransfequipo;
        this.spgestion = spgestion;
        this.spordentrabajo = spordentrabajo;
        this.codigo = codigo;
        this.fkordenorigen = fkordenorigen;
        this.data = data;
        this.estado = estado;
    }
    public Sptransfequipo(int pktransfequipo, Spgestion spgestion, Spordentrabajo spordentrabajo, String codigo, Date fecha, int fkordenorigen, String observacion, String data, char estado, Set spdettransfequipos) {
       this.pktransfequipo = pktransfequipo;
       this.spgestion = spgestion;
       this.spordentrabajo = spordentrabajo;
       this.codigo = codigo;
       this.fecha = fecha;
       this.fkordenorigen = fkordenorigen;
       this.observacion = observacion;
       this.data = data;
       this.estado = estado;
       this.spdettransfequipos = spdettransfequipos;
    }
   
    public int getPktransfequipo() {
        return this.pktransfequipo;
    }
    
    public void setPktransfequipo(int pktransfequipo) {
        this.pktransfequipo = pktransfequipo;
    }
    public Spgestion getSpgestion() {
        return this.spgestion;
    }
    
    public void setSpgestion(Spgestion spgestion) {
        this.spgestion = spgestion;
    }
    public Spordentrabajo getSpordentrabajo() {
        return this.spordentrabajo;
    }
    
    public void setSpordentrabajo(Spordentrabajo spordentrabajo) {
        this.spordentrabajo = spordentrabajo;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public int getFkordenorigen() {
        return this.fkordenorigen;
    }
    
    public void setFkordenorigen(int fkordenorigen) {
        this.fkordenorigen = fkordenorigen;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
    public String getData() {
        return this.data;
    }
    
    public void setData(String data) {
        this.data = data;
    }
    public char getEstado() {
        return this.estado;
    }
    
    public void setEstado(char estado) {
        this.estado = estado;
    }
    public Set getSpdettransfequipos() {
        return this.spdettransfequipos;
    }
    
    public void setSpdettransfequipos(Set spdettransfequipos) {
        this.spdettransfequipos = spdettransfequipos;
    }




}


