package com.grupo06sa.emailweb.modelos;
// Generated 25-06-2017 07:52:36 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Sptransfpersonal generated by hbm2java
 */
public class Sptransfpersonal  implements java.io.Serializable {


     private int pktransfpersonal;
     private Spgestion spgestion;
     private Spordentrabajo spordentrabajoByFkordendestino;
     private Spordentrabajo spordentrabajoByFkordenorigen;
     private String codigo;
     private Date fecha;
     private String observacion;
     private String data;
     private Character estado;
     private Set spdettransfpersonals = new HashSet(0);

    public Sptransfpersonal() {
    }

	
    public Sptransfpersonal(int pktransfpersonal, Spgestion spgestion, Spordentrabajo spordentrabajoByFkordendestino, Spordentrabajo spordentrabajoByFkordenorigen, String codigo) {
        this.pktransfpersonal = pktransfpersonal;
        this.spgestion = spgestion;
        this.spordentrabajoByFkordendestino = spordentrabajoByFkordendestino;
        this.spordentrabajoByFkordenorigen = spordentrabajoByFkordenorigen;
        this.codigo = codigo;
    }
    public Sptransfpersonal(int pktransfpersonal, Spgestion spgestion, Spordentrabajo spordentrabajoByFkordendestino, Spordentrabajo spordentrabajoByFkordenorigen, String codigo, Date fecha, String observacion, String data, Character estado, Set spdettransfpersonals) {
       this.pktransfpersonal = pktransfpersonal;
       this.spgestion = spgestion;
       this.spordentrabajoByFkordendestino = spordentrabajoByFkordendestino;
       this.spordentrabajoByFkordenorigen = spordentrabajoByFkordenorigen;
       this.codigo = codigo;
       this.fecha = fecha;
       this.observacion = observacion;
       this.data = data;
       this.estado = estado;
       this.spdettransfpersonals = spdettransfpersonals;
    }
   
    public int getPktransfpersonal() {
        return this.pktransfpersonal;
    }
    
    public void setPktransfpersonal(int pktransfpersonal) {
        this.pktransfpersonal = pktransfpersonal;
    }
    public Spgestion getSpgestion() {
        return this.spgestion;
    }
    
    public void setSpgestion(Spgestion spgestion) {
        this.spgestion = spgestion;
    }
    public Spordentrabajo getSpordentrabajoByFkordendestino() {
        return this.spordentrabajoByFkordendestino;
    }
    
    public void setSpordentrabajoByFkordendestino(Spordentrabajo spordentrabajoByFkordendestino) {
        this.spordentrabajoByFkordendestino = spordentrabajoByFkordendestino;
    }
    public Spordentrabajo getSpordentrabajoByFkordenorigen() {
        return this.spordentrabajoByFkordenorigen;
    }
    
    public void setSpordentrabajoByFkordenorigen(Spordentrabajo spordentrabajoByFkordenorigen) {
        this.spordentrabajoByFkordenorigen = spordentrabajoByFkordenorigen;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
    public String getData() {
        return this.data;
    }
    
    public void setData(String data) {
        this.data = data;
    }
    public Character getEstado() {
        return this.estado;
    }
    
    public void setEstado(Character estado) {
        this.estado = estado;
    }
    public Set getSpdettransfpersonals() {
        return this.spdettransfpersonals;
    }
    
    public void setSpdettransfpersonals(Set spdettransfpersonals) {
        this.spdettransfpersonals = spdettransfpersonals;
    }




}


