package com.grupo06sa.emailweb.modelos;
// Generated 25-06-2017 07:52:36 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Spturno generated by hbm2java
 */
public class Spturno  implements java.io.Serializable {


     private int pkturno;
     private Spordentrabajo spordentrabajo;
     private String codigo;
     private String descripcion;
     private Set sppartediarios = new HashSet(0);

    public Spturno() {
    }

	
    public Spturno(int pkturno) {
        this.pkturno = pkturno;
    }
    public Spturno(int pkturno, Spordentrabajo spordentrabajo, String codigo, String descripcion, Set sppartediarios) {
       this.pkturno = pkturno;
       this.spordentrabajo = spordentrabajo;
       this.codigo = codigo;
       this.descripcion = descripcion;
       this.sppartediarios = sppartediarios;
    }
   
    public int getPkturno() {
        return this.pkturno;
    }
    
    public void setPkturno(int pkturno) {
        this.pkturno = pkturno;
    }
    public Spordentrabajo getSpordentrabajo() {
        return this.spordentrabajo;
    }
    
    public void setSpordentrabajo(Spordentrabajo spordentrabajo) {
        this.spordentrabajo = spordentrabajo;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getSppartediarios() {
        return this.sppartediarios;
    }
    
    public void setSppartediarios(Set sppartediarios) {
        this.sppartediarios = sppartediarios;
    }




}


